name = "L2OALM"
uuid = "f31bfc7b-7b5d-4cc3-b76b-1af281ce159d"
authors = ["Andrew <arosemberg3@gatech.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
